### ISSUE TITLE
release wheel for 3.10

### ISSUE THREAD

**Issue by ianhi** [zarr-developers/numcodecs#308]
#### Minimal, reproducible code sample, a copy-pastable example if possible
```
mamba create -n test python=3.10
pip install numcodecs
```

#### Problem description
Above code spends some time building the wheel. Which may fail on some systems and also slows down install times. It would be great to bump CI python versions and release the new wheels.

#### Version and installation information

Please provide the following:

* Value of ``numcodecs.__version__`` 0.9.1
* Version of Python interpreter 3.10
* Operating system (Linux/Windows/Mac) linux
* How NumCodecs was installed (e.g., "using pip into virtual environment", or "using conda"): pip

**Comment by martindurant** [comment]
I think conda-forge has built for 3.10 already, if that will do.

**Comment by ianhi** [comment]
> I think conda-forge has built for 3.10 already, if that will do.

That's a good workaround - but I expect that there will be people who use pip primarily  who will also run into this. e.g. i ran into this when doing pip install of different pacakge and it caught me off gaurd. No rush from me to fix, just wanted to bring it up

**Comment by martindurant** [comment]
Sure, we need to update the release too.

**Comment by jakirkham** [comment]
We build wheels with [`cibuildwheel` in this GH Action]( https://github.com/zarr-developers/numcodecs/blob/master/.github/workflows/wheel.yaml ). AFAICT `cibuildwheel` already supports Python 3.10. So that should just work.

Currently CI doesn't [cover Python 3.10]( https://github.com/zarr-developers/numcodecs/blob/a81856efbf8dfd8ea925acaac01235a096d285e4/.github/workflows/ci-linux.yaml#L11 ). So adding that would be good to do.

If someone would like to do a PR to add Python 3.10, that would be a good first step towards addressing this. Not expecting any major issues there, but if they come happy to discuss. @ianhi would you be interested in giving this a try? 🙂

**Comment by martindurant** [comment]
> cibuildwheel already supports Python 3.10

Yes, only if it is up to date

**Comment by henryiii** [comment]
This is one of the remaining not-on-3.10 yet wheels pyodide https://github.com/pyodide/pyodide/issues/978. Do you still support Python 2? If so, them bumping to cibuildwheel 2.3.1 will drop 2.7 & 3.5 wheels - which is probably a good idea, since the only supported way to make them today is to use manylinux1, which is past EOL and hanging on by a thread. But you can split the job in two and use old cibuildwheel for old Python versions if that's the case. Otherwise, it should be a pretty simple bump.

**Comment by henryiii** [comment]
Excellent, no Python <3.6 support, so should be a simple version bump. If you use our Action, you can even have GitHub Dependabot update this regularly for you.

Minor request, could you please remove the <4 from your Python requires? It causes issues for locking packages managers, and is discouraged. See https://iscinumpy.dev/post/bound-version-constraints/, https://discuss.python.org/t/requires-python-upper-limits, and https://github.com/cjolowicz/cookiecutter-hypermodern-python/issues/1154 for some context / issues related to this.

**Comment by jakirkham** [comment]
> Excellent, no Python <3.6 support, so should be a simple version bump. If you use our Action, you can even have GitHub Dependabot update this regularly for you.

What would need to be done to set this up?

**Comment by jakirkham** [comment]
On a side note, would be curious to learn more about how Pyodide & Zarr are being used together. Opened issue ( https://github.com/zarr-developers/community/issues/43 ) for discussion on this 🙂

**Comment by jakirkham** [comment]
Wheels are now available for testing under [`0.10.0a2`]( https://pypi.org/project/numcodecs/0.10.0a2/ ). Thanks @joshmoore for producing those 😄

**Comment by peterdudfield** [comment]
Thanks @jakirkham - worked for me

**Comment by joshmoore** [comment]
Closing but please speak up if there are any remaining issues.
